version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB}'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - ./db/__init__.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - '${REST_API_PORT}:${REST_API_PORT}'
      - '${WEBSOCKET_PORT}:${WEBSOCKET_PORT}'
